name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy SecurityZines on DO
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_PRIV_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USER }} # User of the server you want to ssh into
     
          script: |
            echo 'Startung the deployment'
            cd www/securityzines.com/
            git pull origin main
            echo 'Deployment successful to digital ocean' 
